import { test, devices, expect } from '@playwright/test'

var homePage = "http://localhost:3000";
var moviesPage = "http://localhost:3000/movies";

test.beforeAll(async () => {
    console.log("Before tests")
})

test.afterAll(async () => {
    console.log('After tests')
})

test('should navigate to the movies page', async ({ page }) => {
    // Start from the index page (the baseURL is set via the webServer in the playwright.config.ts)
    await page.goto(homePage)
    // Find an element with the text 'About Page' and click on it
    await page.click('text=Watch Now')
    // The new URL should be "/about" (baseURL is used there)
    await expect(page).toHaveURL(moviesPage)
    // The new page should contain an h1 with "About Page"
    await expect(page.locator('h1')).toContainText('Movies')
  })

test.describe('Head tag area', () => {
    test('Contains the head tag and its contents', async ({page}) => {
        await page.goto(homePage);
        await expect(page).toHaveTitle("Netflex");
        const metaDescription = page.locator('meta[name="description"]');
        await expect(metaDescription).toHaveAttribute('content', 'Generated by create next app');
        const linkIcon = page.locator('link[rel="icon"]');
        await expect(linkIcon).toHaveAttribute('href','/favicon.ico')
    })
})



test.describe('check background image', () => {
    test('Should contain a background image', async ({ page }) => {
        await page.goto(homePage);
        await expect(page).toHaveScreenshot('background.png');
    })
})

