import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import record from "../data/netflix.json";
import Link from "next/link";
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  console.log(record);
  return (
    <>
      <Head>
        <title>Netflex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className={styles.showcase} id="show">
          <div className={styles.showcaseTop}>
            <Image
              style={{ cursor: "pointer", display: menuOpen ? "none" : "block" }}
              onClick={() => setMenuOpen(true)}
              width={60}
              height={60}
              src={require("public/square.png")}
              className={styles.menubar}
              alt="menu"
            />
            <div
              className={styles.menudrop}
              style={{ display: menuOpen ? "block" : "none" }}
            >
              <h1 className={styles.cross} onClick={() => setMenuOpen(false)}>
                x
              </h1>
              <ul className={styles.menulink}>
                <Link href="/">Home</Link>
                <Link href="/movies">Movies</Link>
              </ul>
            </div>
            
            <Image
              alt="netflix"
              id="logo"
              className={styles.netfliximg}
              src={require("public/video-camera.png")}
            />
          </div>
          <div className={styles.showcaseContent}>
            <h1 className={styles.h1} id="hsize">See what's next</h1>
            <p className={styles.p} id="psize">Watch anywhere With Family & Friends!</p>
            <Link href="/movies" className={styles.btn} id="btnsize">
              Watch Now
            </Link>
          </div>
        </header>
      </main>
    </>
  );
}
