import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import record from "../data/movieData.json";
import Link from "next/link";
import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  console.log(record);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} >
      <div className={styles.backbtn}>
      <Link href="/">Back</Link>
      </div>
      <h1 className={styles.title} id="none">Choose your movies</h1>
        <div className={styles.card} id="cardWidth">
        {record.map((rec, index) => {
          return (
              <div key={index} className={styles.cardcontent} >
                <img src={`https://image.tmdb.org/t/p/w400/${rec.poster_path}`} className={styles.movimg} id="img"/>
                <>{rec.genres == "Crime" ? <div>{rec.genres}</div> : <></>}</>
                <div className={styles.movtitle}>{rec.title}</div>
                <div className={styles.desc}>
                  <p>SUMMARY</p>
                  <div>{rec.overview}</div>
                  <button className={styles.watch}>Watch</button>
                </div>
              </div>
          );
        })}
        </div>
      </main>
    </>
  );
}
